# Compiler toolchain paths
clang: /usr/bin/clang                # Path to clang executable
clangpp: /usr/bin/clang++             # Path to clang++ executable
opt: /usr/bin/opt                     # Path to LLVM opt tool
flang: /usr/bin/flang                 # Path to Fortran frontend (optional)
llvm_extract:
llvm_nm:
llvm_dis:
llvm_as:
llvm_mca:
llc:
tokenizer:
alive2:

# Extra linking libraries (optional, if you use custom LLVM passes)
extralib: /usr/lib/llvm-extra

# WANDB API key for experiment tracking (optional)
wandb: your-wandb-api-key-here

# Path to the LLVM source root (e.g., if you need access to .td, .inc files)
llvm: /home/yourname/llvm-project